### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, stat '/Users/Pong/subl'

### ISSUE THREAD

**Issue by paweenruk** [styczynski/atom-terminal-panel#102]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.6
**Thrown From**: [atom-terminal-panel](https://github.com/isis97/atom-terminal-panel) package, v4.4.4
### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat '/Users/Pong/subl'

```
At fs.js:897

Error: ENOENT: no such file or directory, stat '/Users/Pong/subl'
    at Error (native)
    at fs.statSync (fs.js:897:18)
    at Object.fs.statSync (ATOM_SHELL_ASAR.js:264:16)
    at ATPOutputView.module.exports.ATPOutputView._fileInfoHtml (/Users/Pong/.atom/packages/atom-terminal-panel/lib/atp-view.coffee:1081:19)
    at /Users/Pong/.atom/packages/atom-terminal-panel/lib/atp-view.coffee:909:25
    at Array.forEach (native)
    at ATPOutputView.module.exports.ATPOutputView.ls (/Users/Pong/.atom/packages/atom-terminal-panel/lib/atp-view.coffee:908:11)
    at module.exports.ls.command (/Users/Pong/.atom/packages/atom-terminal-panel/lib/atp-builtins-commands.coffee:25:20)
    at ATPOutputView.module.exports.ATPOutputView.exec_ (/Users/Pong/.atom/packages/atom-terminal-panel/lib/atp-view.coffee:520:17)
    at ATPOutputView.module.exports.ATPOutputView.exec (/Users/Pong/.atom/packages/atom-terminal-panel/lib/atp-view.coffee:456:13)
    at ATPOutputView.module.exports.ATPOutputView.onCommand (/Users/Pong/.atom/packages/atom-terminal-panel/lib/atp-view.coffee:700:12)
    at Object.<anonymous> (/Users/Pong/.atom/packages/atom-terminal-panel/lib/atp-view.coffee:193:8)
    at Object.call (/Users/Pong/.atom/packages/atom-terminal-panel/node_modules/jquery-autocomplete-js/autocomplete.js:52:25)
    at Object.rs.onEnter (/Users/Pong/.atom/packages/atom-terminal-panel/node_modules/jquery-autocomplete-js/autocomplete.js:663:33)
    at HTMLInputElement.keyDownHandler (/Users/Pong/.atom/packages/atom-terminal-panel/node_modules/jquery-autocomplete-js/autocomplete.js:885:11)
    at HTMLInputElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLInputElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "jslint",
      "react"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
angularjs, v0.3.5
atom-terminal-panel, v4.4.4
emmet, v2.4.3
jshint, v1.8.5
language-babel, v2.32.1
language-scala, v1.1.6
merge-conflicts, v1.4.4
react-es6-snippets, v0.3.0
remote-edit, v1.8.24

# Dev
No dev packages
```

**Comment by mccstan** [comment]
Just remove this file : rm ~/subl
