### ISSUE TITLE
Uncaught TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by rakshazi** [styczynski/atom-terminal-panel#108]
Hello!

Steps to reproduce
1. Install package and try to use it with any opened file
2. `touch ~/.atom/terminal-commands.json`  doesn't help

**Atom Version**: 1.10.2
**Electron Version**: 1.4.1
**System**: "Manjaro Linux"
**Thrown From**: [atom-terminal-panel](https://github.com/isis97/atom-terminal-panel) package, v4.4.4
### Stack Trace

Uncaught TypeError: Path must be a string. Received undefined

```
At path.js:7

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at extname (path.js:1433:5)
    at ATPOutputView.module.exports.ATPOutputView.getCwd (/home/rakshazi/.atom/packages/atom-terminal-panel/lib/atp-view.coffee:1318:15)
    at BuiltinVariables.parseFull (/home/rakshazi/.atom/packages/atom-terminal-panel/lib/atp-builtins-variables.coffee:149:75)
    at BuiltinVariables.parseHtml (/home/rakshazi/.atom/packages/atom-terminal-panel/lib/atp-builtins-variables.coffee:90:10)
    at ATPOutputView.module.exports.ATPOutputView.parseTemplate (/home/rakshazi/.atom/packages/atom-terminal-panel/lib/atp-view.coffee:423:34)
    at ATPPanel.module.exports.ATPPanel.updateStatusBar (/home/rakshazi/.atom/packages/atom-terminal-panel/lib/atp-panel.coffee:77:37)
    at ATPPanel.module.exports.ATPPanel.toggle (/home/rakshazi/.atom/packages/atom-terminal-panel/lib/atp-panel.coffee:155:6)
    at atom-workspace.atom.commands.add.atom-terminal-panel:toggle (/home/rakshazi/.atom/packages/atom-terminal-panel/lib/atp-panel.coffee:42:41)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/lib/atom/src/command-registry.js:260:29)
    at /usr/lib/atom/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/lib/atom/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/lib/atom/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/lib/atom/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/usr/lib/atom/src/window-event-handler.js:3:61)
```
### Commands

```
     -3:43.1.0 incompatible-packages:view (div.incompatible-packages-status.inline-block.text.text-error)
     -2:02.9.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -1:57.7.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -1:56.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:56.8.0 settings-view:install-packages-and-themes (atom-text-editor.editor)
     -1:54.4.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -1:53.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.7.0 atom-terminal-panel:toggle-autocompletion (atom-text-editor.editor.is-focused)
     -0:00.2.0 atom-terminal-panel:toggle (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "autoHideMenuBar": true,
    "excludeVcsIgnoredPaths": false,
    "openEmptyEditorOnStart": false,
    "themes": [
      "one-dark-ui",
      "atom-material-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-autocomplete-php, v0.19.4 (active)
atom-material-syntax, v0.4.6 (active)
atom-terminal-panel, v4.4.4 (active)
docblockr, v0.8.5 (active)
file-icons, v1.7.19 (active)
linter, v1.11.16 (active)
linter-php, v1.2.0 (active)
nucleus-dark-ui, v0.10.5 (inactive)
php-cs-fixer, v2.5.9 (active)
remote-sync, v4.1.4 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (active)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by blacksponge** [comment]
I've experimented the same issue, any help will be well appreciated. Furthermore I got this problem while Atom tried to activate the module. :cry:
