### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, stat '/home/robbie/.ecryptfs'

### ISSUE THREAD

**Issue by robjloranger** [styczynski/atom-terminal-panel#43]
1. try to list files in your home directory with home folder encryption

I assume this is a hard link issue

**Atom Version**: 1.0.2
**System**: Ubuntu Wily
**Thrown From**: [atom-terminal-panel](https://github.com/isis97/atom-terminal-panel) package, v4.4.4
### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat '/home/robbie/.ecryptfs'

```
At fs.js:846

Error: ENOENT: no such file or directory, stat '/home/robbie/.ecryptfs'
  at Error (native)
  at fs.statSync (fs.js:846:18)
  at Object.fs.statSync (ATOM_SHELL_ASAR.js:206:16)
  at ATPOutputView.module.exports.ATPOutputView._fileInfoHtml (/home/robbie/.atom/packages/atom-terminal-panel/lib/atp-view.coffee:1081:19)
  at /home/robbie/.atom/packages/atom-terminal-panel/lib/atp-view.coffee:909:25
  at Array.forEach (native)
  at ATPOutputView.module.exports.ATPOutputView.ls (/home/robbie/.atom/packages/atom-terminal-panel/lib/atp-view.coffee:908:11)
  at module.exports.ls.command (/home/robbie/.atom/packages/atom-terminal-panel/lib/atp-builtins-commands.coffee:25:20)
  at ATPOutputView.module.exports.ATPOutputView.exec_ (/home/robbie/.atom/packages/atom-terminal-panel/lib/atp-view.coffee:520:17)
  at ATPOutputView.module.exports.ATPOutputView.exec (/home/robbie/.atom/packages/atom-terminal-panel/lib/atp-view.coffee:456:13)
  at ATPOutputView.module.exports.ATPOutputView.onCommand (/home/robbie/.atom/packages/atom-terminal-panel/lib/atp-view.coffee:700:12)
  at Object.<anonymous> (/home/robbie/.atom/packages/atom-terminal-panel/lib/atp-view.coffee:193:8)
  at Object.call (/home/robbie/.atom/packages/atom-terminal-panel/node_modules/jquery-autocomplete-js/autocomplete.js:52:25)
  at Object.rs.onEnter (/home/robbie/.atom/packages/atom-terminal-panel/node_modules/jquery-autocomplete-js/autocomplete.js:663:33)
  at HTMLInputElement.keyDownHandler (/home/robbie/.atom/packages/atom-terminal-panel/node_modules/jquery-autocomplete-js/autocomplete.js:885:11)
  at HTMLInputElement.jQuery.event.dispatch (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at HTMLInputElement.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```
### Commands

```
```
### Config

``` json
{
  "core": {},
  "atom-terminal-panel": {}
}
```
### Installed Packages

``` coffee
# User
atom-terminal-panel, v4.4.4

# Dev
No dev packages
```

**Comment by ghost** [comment]
closing stale
