### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, stat '/Users/<User>/.spumux'

### ISSUE THREAD

**Issue by m-oscartong** [styczynski/atom-terminal-panel#82]
[Enter steps to reproduce below:]
1. Install atom-terminal-panel
2. Launch the panel
3. Type in `ls`
4. Error

**Atom Version**: 1.3.1
**System**: Mac OS X 10.11.1
**Thrown From**: [atom-terminal-panel](https://github.com/isis97/atom-terminal-panel) package, v4.4.4
### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat '/Users/<User>/.spumux'

```
At fs.js:854

Error: ENOENT: no such file or directory, stat '/Users/<User>/.spumux'
    at Error (native)
    at fs.statSync (fs.js:854:18)
    at Object.fs.statSync (ATOM_SHELL_ASAR.js:225:16)
    at ATPOutputView.module.exports.ATPOutputView._fileInfoHtml (/Users/<User>/.atom/packages/atom-terminal-panel/lib/atp-view.coffee:1081:19)
    at /Users/<User>/.atom/packages/atom-terminal-panel/lib/atp-view.coffee:909:25
    at Array.forEach (native)
    at ATPOutputView.module.exports.ATPOutputView.ls (/Users/<User>/.atom/packages/atom-terminal-panel/lib/atp-view.coffee:908:11)
    at module.exports.ls.command (/Users/<User>/.atom/packages/atom-terminal-panel/lib/atp-builtins-commands.coffee:25:20)
    at ATPOutputView.module.exports.ATPOutputView.exec_ (/Users/<User>/.atom/packages/atom-terminal-panel/lib/atp-view.coffee:520:17)
    at ATPOutputView.module.exports.ATPOutputView.exec (/Users/<User>/.atom/packages/atom-terminal-panel/lib/atp-view.coffee:456:13)
    at ATPOutputView.module.exports.ATPOutputView.onCommand (/Users/<User>/.atom/packages/atom-terminal-panel/lib/atp-view.coffee:700:12)
    at Object.<anonymous> (/Users/<User>/.atom/packages/atom-terminal-panel/lib/atp-view.coffee:193:8)
    at Object.call (/Users/<User>/.atom/packages/atom-terminal-panel/node_modules/jquery-autocomplete-js/autocomplete.js:52:25)
    at Object.rs.onEnter (/Users/<User>/.atom/packages/atom-terminal-panel/node_modules/jquery-autocomplete-js/autocomplete.js:663:33)
    at HTMLInputElement.keyDownHandler (/Users/<User>/.atom/packages/atom-terminal-panel/node_modules/jquery-autocomplete-js/autocomplete.js:885:11)
    at HTMLInputElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLInputElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```
### Commands

```
     -0:57.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {},
  "atom-terminal-panel": {}
}
```
### Installed Packages

``` coffee
# User
atom-terminal-panel, v4.4.4

# Dev
No dev packages
```

**Comment by pycckuu** [comment]
The same here

**Comment by pycckuu** [comment]
is ```.spumux'``` is link in your case?
